services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axolotl_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - node

  node:
    image: node:20
    container_name: axolotl_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173-5199:5173-5199"  # expose a range for Vite
    command: npm run dev
    tty: true